name: release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    name: ${{ matrix.target }}
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        target: [ x64, x86 ]
    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-tags: true
        fetch-depth: 0
    - name: install bison/flex
      run: |
        choco install winflexbison3
    - name: alias bison/flex
      run: |
        $dir = (Get-Command win_bison).Source | Split-Path
        Copy-Item "$dir\win_bison.exe" "$dir\bison.exe"
        Copy-Item "$dir\win_flex.exe" "$dir\flex.exe"
    - name: 'build'
      run: |
        cmake --preset msvc-static-${{ matrix.target }}
        cmake --build --preset msvc-static-${{ matrix.target }}-relmin
    - name: 'release'
      run: |
        Compress-Archive -Path build\${{ matrix.target }}\bin\*.exe -Destination rgbdsxp-${{ matrix.target }}.zip
        gh release upload ${{github.event.release.tag_name}} rgbdsxp-${{ matrix.target }}.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}